### ISSUE TITLE
Package is invalid. Details: 'Could not load extension icon 'SCP-logo-16.png'.'.

### ISSUE THREAD

**Issue by AJMansfield** [FiftyNine/SCPper#24]
When attempting to install from the chrome web store on Chromium Version 53.0.2785.143, the installation fails and I recieve an error dialogue with this message:

    Package is invalid. Details: 'Could not load extension icon 'SCP-logo-16.png'.'.

**Comment by FiftyNine** [comment]
Well, this is weird. It installs just fine for me, although I'm using the latest Chrome (54.0.2840.99 m). I'll test it some more when I get home from work, but I haven't changed anything in SCPper in a while, so I can't imagine what could be wrong with the package. Right now my bet is on store/Chrome hiccup. Have you tried re-downloading/re-installing it?

**Comment by AJMansfield** [comment]
I haven't actually installed it before.

**Comment by AJMansfield** [comment]
I did try installing it several times though.

**Comment by RealityUnhinged** [comment]
I'm getting the same message. I think it may have something to do with Chromium vs. Chrome...

-RU =)

**Comment by SeraDomiCher** [comment]
I'm having this problem too, (I'm on a Chromebook, if that changes anything.)

**Comment by FiftyNine** [comment]
Well, it only took me 2 and a half years, but now this extensions works on unix systems.
