### ISSUE TITLE
Look Who Rated This Not Accessible

### ISSUE THREAD

**Issue by Rogay** [FiftyNine/SCPper#25]
The total up/down vote breakdown list is inaccessible when the extension is active. Clicking on the Rating option at the bottom of a page does nothing, when it should show the "Look who rated this page" option along with a rating module.

**Comment by FiftyNine** [comment]
Fixed in 6bd8d9da19e01543c6de66febce70d70f9087c3e
Changes will go live in a couple of hours.
Thanks for reporting this issue!
