### ISSUE TITLE
add support for scp series 8 (7000-7999) - series 11 (1000-1999)

### ISSUE THREAD

**Issue by 2BoredPlayer** [FiftyNine/SCPper#31]
self explanatory. only series 8 has been released but why im saying go through series 9-11 is to proofread this extension in the future.

**Comment by FiftyNine** [comment]
Thanks you for bringing this to my attention.
Updates have been pushed to both Chrome and Firefox extensions, although they may take some time to pass review and get published.

**Comment by 2BoredPlayer** [comment]
@FiftyNine could this also be put on the website [www.scpper.com](https://www.scpper.com/) as well?

**Comment by FiftyNine** [comment]
> @FiftyNine could this also be put on the website [www.scpper.com](https://www.scpper.com/) as well?

scpper.com grabs all pages from the wiki regardless of whether they are listed on some page or not.
That being said I updated crawler so it should collect alternative titles for main list articles from series 8+ pages.
